
import java.awt.Desktop;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wei0000
 */
public class csvToolGUI extends javax.swing.JFrame {
   public static String userDir = System.getProperty("user.dir");
   public static File filePath1 = null;
   public static File filePath2 = null;
    /**
     * Creates new form csvToolGUI
     */
    public csvToolGUI() {
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BrowseFile = new javax.swing.JFileChooser();
        Text1 = new javax.swing.JLabel();
        ConvertFilePath1 = new javax.swing.JTextField();
        ConvertRun = new javax.swing.JButton();
        OpenPath1 = new javax.swing.JButton();
        Browser1 = new javax.swing.JButton();
        Text2 = new javax.swing.JLabel();
        ConvertFilePath2 = new javax.swing.JTextField();
        ConvertRun2 = new javax.swing.JButton();
        OpenPath2 = new javax.swing.JButton();
        Browser2 = new javax.swing.JButton();
        versionNumber = new javax.swing.JLabel();
        ViewLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESRI_CSV_Converter_Tool");

        Text1.setText("Select the Excel file that needs to be converted. ");

        ConvertFilePath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertFilePath1ActionPerformed(evt);
            }
        });

        ConvertRun.setText("Generate");
        ConvertRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertRunActionPerformed(evt);
            }
        });

        OpenPath1.setText("Open the converted File Folder");
        OpenPath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenPath1ActionPerformed(evt);
            }
        });

        Browser1.setText("Browse File");
        Browser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browser1ActionPerformed(evt);
            }
        });

        Text2.setText("Select the Excel file that needs to be converted into separated language");

        ConvertFilePath2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertFilePath2ActionPerformed(evt);
            }
        });

        ConvertRun2.setText("Generate");
        ConvertRun2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertRun2ActionPerformed(evt);
            }
        });

        OpenPath2.setText("Open the converted File Folder");
        OpenPath2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenPath2ActionPerformed(evt);
            }
        });

        Browser2.setText("Browse File");
        Browser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browser2ActionPerformed(evt);
            }
        });

        versionNumber.setText("version 1.0");

        ViewLog.setText("View Log File");
        ViewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(versionNumber)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ConvertFilePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Browser1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Text2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ConvertFilePath2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ViewLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Browser2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(ConvertRun2)
                .addGap(83, 83, 83)
                .addComponent(OpenPath2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(ConvertRun)
                .addGap(80, 80, 80)
                .addComponent(OpenPath1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Text1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(versionNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Browser1)
                    .addComponent(ConvertFilePath1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenPath1)
                    .addComponent(ConvertRun))
                .addGap(38, 38, 38)
                .addComponent(Text2)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertFilePath2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Browser2))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertRun2)
                    .addComponent(OpenPath2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(ViewLog)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertRunActionPerformed
        // TODO add your handling code here:
        String fileName = ConvertFilePath1.getText();
        ReadExcel re = new ReadExcel();
        String[][] csv = null;
        try{
        csv = re.readFile(fileName);
        }
        catch(Exception e){
            re.log("Some exception occurs" + e.getMessage());
        }
    }//GEN-LAST:event_ConvertRunActionPerformed

    private void ConvertFilePath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertFilePath1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConvertFilePath1ActionPerformed

    private void Browser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browser1ActionPerformed
        // TODO add your handling code here:
        FileFilter ft = new FileNameExtensionFilter("Excel File (*.xlsx)","xlsx");
        BrowseFile.addChoosableFileFilter(ft);
        String file_name = null;
        do{
        int returnVal = BrowseFile.showOpenDialog(this);
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION){
            File file = BrowseFile.getSelectedFile(); ;
            file_name = file.toString();
            filePath1 = new File(file_name.substring(0,file_name.lastIndexOf(File.separator)));
            ConvertFilePath1.setText(file_name);
            
            if(!(file_name.endsWith(".xlsx"))){
               JOptionPane.showMessageDialog(null, "The file you selected is not xlsx file, please select the file again.");
               ConvertFilePath1.setText("");
               file_name = null;
            }
         }
        }while(!(file_name.endsWith(".xlsx")));
    }//GEN-LAST:event_Browser1ActionPerformed

    private void OpenPath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenPath1ActionPerformed
        // TODO add your handling code here:
        try{
            if(Desktop.isDesktopSupported()){
                Desktop.getDesktop().open(filePath1);
            }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_OpenPath1ActionPerformed

    private void ConvertFilePath2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertFilePath2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConvertFilePath2ActionPerformed

    private void Browser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browser2ActionPerformed
        // TODO add your handling code here:
        FileFilter ft = new FileNameExtensionFilter("Excel File (*.xlsx)","xlsx");
        BrowseFile.addChoosableFileFilter(ft);
        String file_name = null;
        do{
        int returnVal = BrowseFile.showOpenDialog(this);
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION){
            File file = BrowseFile.getSelectedFile(); ;
            file_name = file.toString();
            filePath2 = new File(file_name.substring(0,file_name.lastIndexOf(File.separator)));
            ConvertFilePath2.setText(file_name);
            
            if(!(file_name.endsWith(".xlsx"))){
               JOptionPane.showMessageDialog(null, "The file you selected is not xlsx file, please select the file again.");
               ConvertFilePath2.setText("");
               file_name = null;
            }
         }
        }while(!(file_name.endsWith(".xlsx")));
    }//GEN-LAST:event_Browser2ActionPerformed

    private void OpenPath2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenPath2ActionPerformed
        // TODO add your handling code here:
         try{
            if(Desktop.isDesktopSupported()){
                Desktop.getDesktop().open(filePath2);
            }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_OpenPath2ActionPerformed

    private void ConvertRun2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertRun2ActionPerformed
        // TODO add your handling code here:
        Input ip = new Input();
        String file2 = ConvertFilePath2.getText();
      try {
           Input.searchFile(file2);
       } catch (Exception ex) {
           Logger.getLogger(csvToolGUI.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_ConvertRun2ActionPerformed

    private void ViewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLogActionPerformed
        // TODO add your handling code here:
        try{
            Process p = Runtime.getRuntime().exec("C:\\Program Files (x86)\\Notepad++\\notepad++.exe " + userDir + "\\log.txt");
            p.waitFor();
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_ViewLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(csvToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(csvToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(csvToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(csvToolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new csvToolGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser BrowseFile;
    private javax.swing.JButton Browser1;
    private javax.swing.JButton Browser2;
    private javax.swing.JTextField ConvertFilePath1;
    private javax.swing.JTextField ConvertFilePath2;
    private javax.swing.JButton ConvertRun;
    private javax.swing.JButton ConvertRun2;
    private javax.swing.JButton OpenPath1;
    private javax.swing.JButton OpenPath2;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JButton ViewLog;
    private javax.swing.JLabel versionNumber;
    // End of variables declaration//GEN-END:variables
}
